kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "<%= projectName %>.fullname" . }}
  labels:
    app: {{ template "<%= projectName %>.name" . }}-<%= apiName %>
    chart: {{ template "<%= projectName %>.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
<% if(apiIngressClass) { -%>
    kubernetes.io/ingress.class: "<%= apiIngressClass %>"
<% } -%>
spec:
<% if(apiTlsEnabled) { -%>
  tls:
<% if(apiTlsHost) { -%>
    - hosts:
      - <%= apiTlsHost %>
<% } -%>
<% if(apiTlsSecret) { -%>
      secretName: <%= apiTlsSecret %>
<%} -%>
<%} -%>
  rules:
<% if(apiHost) { -%>
   -  host: "<%= apiHost %>"
      http:
<% } else { -%>
    - http:
<% } -%>
        paths:
          - path: <%= apiPath %>
            backend:
              serviceName: {{ template "<%= projectName %>.fullname" . }}-<%= apiName %>
              servicePort: http
